using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging.Abstractions;
using SeniorConnect.Infrastructure;
using SeniorConnect.Modules.Identity.Application;
using SeniorConnect.Modules.Identity.Domain;
using SeniorConnect.Modules.Identity.Infrastructure;
using Xunit;

namespace SeniorConnect.Modules.Identity.Tests;

public sealed class IdentityServiceIntegrationTests : IDisposable
{
    private readonly SeniorConnectDbContext _dbContext;
    private readonly IdentityService _identityService;
    private readonly IdentityHashingService _hashing;

    public IdentityServiceIntegrationTests()
    {
        var options = new DbContextOptionsBuilder<SeniorConnectDbContext>()
            .UseInMemoryDatabase(databaseName: $"SeniorConnect_Identity_Tests_{Guid.NewGuid()}")
            .Options;

        var tenantContext = new DefaultTenantContext();
        _dbContext = new SeniorConnectDbContext(options, tenantContext);

        _hashing = new IdentityHashingService();
        var passwordHasher = new PasswordHasher();
        var smsSender = new SmsSender(NullLogger<SmsSender>.Instance);
        var emailSender = new EmailSender(NullLogger<EmailSender>.Instance);

        var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["Jwt:SecretKey"] = "SeniorConnect_super_secret_test_key_1234567890_test_only",
                ["Jwt:Issuer"] = "SeniorConnect.Tests",
                ["Jwt:Audience"] = "SeniorConnect.Tests.Client"
            })
            .Build();

        var tokenService = new JwtTokenService(_dbContext, _hashing, config);
        var otpService = new OtpService(_dbContext, _hashing, smsSender, emailSender);
        var trustCalculator = new TrustLevelCalculator();
        var capabilityService = new CapabilityService(_dbContext);

        _identityService = new IdentityService(
            _dbContext,
            otpService,
            tokenService,
            passwordHasher,
            trustCalculator,
            capabilityService,
            _hashing);
    }

    [Fact]
    public async Task RequestPhoneOtp_AndVerify_CreatesUserAndReturnsTokens()
    {
        const string phone = "+436601112233";

        // 1. Request OTP
        var requestResult = await _identityService.RequestPhoneOtpAsync(
            new RequestPhoneOtpRequest(phone, "Anna Muster"),
            ipAddress: "127.0.0.1");

        Assert.True(requestResult.IsSuccess);

        // Fetch challenge from DB
        var challenge = await _dbContext.OtpChallenges.FirstOrDefaultAsync();
        Assert.NotNull(challenge);
        Assert.Equal(_hashing.HashDestination(phone), challenge.DestinationHash);

        // We can find out what code was generated by looking up all 6-digit codes matching the hash
        string? matchedCode = null;
        for (var i = 100_000; i < 1_000_000; i++)
        {
            var testCode = i.ToString(System.Globalization.CultureInfo.InvariantCulture);
            if (_hashing.HashCode(testCode) == challenge.CodeHash)
            {
                matchedCode = testCode;
                break;
            }
        }

        Assert.NotNull(matchedCode);

        // 2. Verify OTP
        var verifyResult = await _identityService.VerifyPhoneOtpAsync(
            new VerifyPhoneOtpRequest(phone, matchedCode, "iPhone 15", IsPersonalDevice: true));

        Assert.True(verifyResult.IsSuccess);
        Assert.NotNull(verifyResult.Value!.AccessToken);
        Assert.NotNull(verifyResult.Value!.RefreshToken);
        Assert.Equal(1, verifyResult.Value!.TrustLevel); // Phone verified = trust level 1

        // Verify user in DB
        var user = await _dbContext.Users.FirstOrDefaultAsync(u => u.Phone == phone);
        Assert.NotNull(user);
        Assert.NotNull(user.PhoneVerifiedAtUtc);
    }

    [Fact]
    public async Task RequestPhoneOtp_WhenRateLimitExceeded_ReturnsRateLimitedError()
    {
        const string phone = "+436609998877";

        // Send 3 requests
        for (var i = 0; i < 3; i++)
        {
            var res = await _identityService.RequestPhoneOtpAsync(
                new RequestPhoneOtpRequest(phone),
                ipAddress: "127.0.0.1");
            Assert.True(res.IsSuccess);
        }

        // 4th request must fail with RATE_LIMITED
        var fourthRes = await _identityService.RequestPhoneOtpAsync(
            new RequestPhoneOtpRequest(phone),
            ipAddress: "127.0.0.1");

        Assert.True(fourthRes.IsFailure);
        Assert.Equal("RATE_LIMITED", fourthRes.Error!.Code);
    }

    [Fact]
    public async Task RefreshToken_RotatesSuccessfully_AndDetectsReuse()
    {
        const string phone = "+436605556677";

        // Setup user and initial token
        var user = User.CreateWithPhone(phone, "Hans");
        user.VerifyPhone();
        _dbContext.Users.Add(user);
        await _dbContext.SaveChangesAsync();

        var tokenService = new JwtTokenService(_dbContext, _hashing, new ConfigurationBuilder().AddInMemoryCollection().Build());
        var (rawRefreshToken, _) = (await tokenService.CreateRefreshTokenAsync(user.Id, "Safari", true)).Value!;

        // 1. Rotate token
        var refreshResult = await _identityService.RefreshTokenAsync(new RefreshTokenRequest(rawRefreshToken));
        Assert.True(refreshResult.IsSuccess);
        Assert.NotEqual(rawRefreshToken, refreshResult.Value!.RefreshToken);

        // 2. Try to reuse old token -> must be rejected with TOKEN_COMPROMISED
        var reuseResult = await _identityService.RefreshTokenAsync(new RefreshTokenRequest(rawRefreshToken));
        Assert.True(reuseResult.IsFailure);
        Assert.Equal("TOKEN_COMPROMISED", reuseResult.Error!.Code);
    }

    public void Dispose()
    {
        _dbContext.Dispose();
    }
}
