// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeniorConnect.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SeniorConnect.Infrastructure.Migrations
{
    [DbContext(typeof(SeniorConnectDbContext))]
    [Migration("20260821214100_Phase1_Init")]
    partial class Phase1_Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeniorConnect.Modules.HelpRequests.Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnName("branch_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnName("category_id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnName("confirmed_at_utc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnName("confirmed_by_user_id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnName("created_at_utc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnName("duration_minutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EventId")
                        .HasColumnName("event_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HelpRequestId")
                        .HasColumnName("help_request_id")
                        .HasColumnType("uuid");

                    b.Property<string>("InsuranceContext")
                        .HasColumnName("insurance_context")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("InsuranceDisclaimerAcceptedAtUtc")
                        .HasColumnName("insurance_disclaimer_accepted_at_utc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("InsuranceDisclaimerAcceptedByUserId")
                        .HasColumnName("insurance_disclaimer_accepted_by_user_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationType")
                        .HasColumnName("location_type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("LoggedAtUtc")
                        .HasColumnName("logged_at_utc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("LoggedByUserId")
                        .HasColumnName("logged_by_user_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnName("notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnName("occurred_on")
                        .HasColumnType("date");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnName("organization_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasColumnName("source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .HasColumnName("status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SubjectUserId")
                        .HasColumnName("subject_user_id")
                        .HasColumnType("uuid");

                    b.Property<string>("TransportMode")
                        .HasColumnName("transport_mode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnName("updated_at_utc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnName("updated_by")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VolunteerUserId")
                        .HasColumnName("volunteer_user_id")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OccurredOn")
                        .HasFilter("status = 'Confirmed'");

                    b.HasIndex("VolunteerUserId", "OccurredOn");

                    b.ToTable("activities", "public", t =>
                        {
                            t.HasCheckConstraint("ck_activities_distinct_parties", "subject_user_id IS NULL OR subject_user_id <> volunteer_user_id");

                            t.HasCheckConstraint("ck_activities_duration", "duration_minutes BETWEEN 1 AND 1440");

                            t.HasCheckConstraint("ck_activities_transport_insurance", "transport_mode <> 'VolunteerPrivateVehicle' OR status <> 'Confirmed' OR insurance_context <> 'Unknown'");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.HelpRequests.Domain.ActivityCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int>("DefaultSafetyLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("default_safety_level");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_blocked");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_key");

                    b.Property<string>("ReferralGroup")
                        .HasColumnType("text")
                        .HasColumnName("referral_group");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("activity_categories", "public", t =>
                        {
                            t.HasCheckConstraint("ck_activity_categories_blocked_needs_referral", "NOT is_blocked OR referral_group IS NOT NULL");

                            t.HasCheckConstraint("ck_activity_categories_safety", "default_safety_level BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.HelpRequests.Domain.ReferralDirectory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NoteKey")
                        .HasColumnType("text")
                        .HasColumnName("note_key");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ReferralGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referral_group");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region_code");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("ReferralGroup", "RegionCode")
                        .HasFilter("is_active");

                    b.ToTable("referral_directory", "public");
                });

            modelBuilder.Entity("SeniorConnect.Modules.Reporting.Domain.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_organization_id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("AtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("IpHash")
                        .HasColumnType("text")
                        .HasColumnName("ip_hash");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("metadata");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.HasKey("Id");

                    b.HasIndex("Action", "AtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_action");

                    b.HasIndex("ActorUserId", "AtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_actor");

                    b.HasIndex("SubjectType", "SubjectId", "AtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_subject");

                    b.ToTable("audit_entries", "public");
                });

            modelBuilder.Entity("SeniorConnect.Modules.Reporting.Domain.Funder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("funders", "public", t =>
                        {
                            t.HasCheckConstraint("ck_funders_status", "status IN ('active','suspended','ended')");

                            t.HasCheckConstraint("ck_funders_type", "type IN ('municipality','foundation','public_body','corporate')");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Reporting.Domain.FunderMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FunderId")
                        .HasColumnType("uuid")
                        .HasColumnName("funder_id");

                    b.Property<DateTimeOffset?>("JoinedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("joined_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Viewer")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Invited")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("funder_memberships", "public", t =>
                        {
                            t.HasCheckConstraint("ck_funder_memberships_role", "role IN ('viewer','admin')");

                            t.HasCheckConstraint("ck_funder_memberships_status", "status IN ('invited','active','suspended','left')");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Reporting.Domain.FunderMonthlyReportView", b =>
                {
                    b.Property<int?>("ActivityCount")
                        .HasColumnType("integer")
                        .HasColumnName("activity_count");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_code");

                    b.Property<int?>("DistinctPeopleSupported")
                        .HasColumnType("integer")
                        .HasColumnName("distinct_people_supported");

                    b.Property<int?>("DistinctVolunteers")
                        .HasColumnType("integer")
                        .HasColumnName("distinct_volunteers");

                    b.Property<Guid>("FunderId")
                        .HasColumnType("uuid")
                        .HasColumnName("funder_id");

                    b.Property<double?>("Hours")
                        .HasColumnType("double precision")
                        .HasColumnName("hours");

                    b.Property<bool>("IsSuppressed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suppressed");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.ToTable((string)null);

                    b.ToView("v_funder_monthly_report", "public");
                });

            modelBuilder.Entity("SeniorConnect.Modules.Reporting.Domain.FundingRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FunderId")
                        .HasColumnType("uuid")
                        .HasColumnName("funder_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ReportingScopeJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("reporting_scope");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.ToTable("funding_relationships", "public", t =>
                        {
                            t.HasCheckConstraint("ck_funding_dates", "valid_until IS NULL OR valid_until > valid_from");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Reporting.Domain.VolunteerHoursView", b =>
                {
                    b.Property<long>("ActivityCount")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_count");

                    b.Property<double>("Hours")
                        .HasColumnType("double precision")
                        .HasColumnName("hours");

                    b.Property<long>("Minutes")
                        .HasColumnType("bigint")
                        .HasColumnName("minutes");

                    b.Property<DateOnly>("OccurredMonth")
                        .HasColumnType("date")
                        .HasColumnName("occurred_month");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date")
                        .HasColumnName("occurred_on");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("VolunteerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("volunteer_user_id");

                    b.ToTable((string)null);

                    b.ToView("v_volunteer_hours", "public");
                });

            modelBuilder.Entity("SeniorConnect.Modules.Identity.Domain.Consent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consent_type");

                    b.Property<string>("DocumentVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_version");

                    b.Property<bool>("Granted")
                        .HasColumnType("boolean")
                        .HasColumnName("granted");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("granted_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IpHash")
                        .HasColumnType("text")
                        .HasColumnName("ip_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("WithdrawnAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("withdrawn_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ConsentType", "GrantedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_consents_user");

                    b.ToTable("consents", "public", t =>
                        {
                            t.HasCheckConstraint("ck_consents_type", "consent_type IN ('terms','privacy','notifications_push','notifications_sms','notifications_email','research_statistics')");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Identity.Domain.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("attempts");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DestinationHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_hash");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IpHash")
                        .HasColumnType("text")
                        .HasColumnName("ip_hash");

                    b.Property<short>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)5)
                        .HasColumnName("max_attempts");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Login")
                        .HasColumnName("purpose");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_otp_cleanup");

                    b.HasIndex("DestinationHash", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_otp_active")
                        .HasFilter("consumed_at_utc IS NULL");

                    b.ToTable("otp_challenges", "public", t =>
                        {
                            t.HasCheckConstraint("ck_otp_attempts", "attempts <= max_attempts");

                            t.HasCheckConstraint("ck_otp_channel", "channel IN ('sms','email')");

                            t.HasCheckConstraint("ck_otp_purpose", "purpose IN ('login','registration','phone_change','email_change','recovery')");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Identity.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceLabel")
                        .HasColumnType("text")
                        .HasColumnName("device_label");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsPersonalDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_personal_device");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user")
                        .HasFilter("revoked_at_utc IS NULL");

                    b.ToTable("refresh_tokens", "public");
                });

            modelBuilder.Entity("SeniorConnect.Modules.Identity.Domain.TrustLevelSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ComputedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("computed_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("ReasonJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ComputedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_trust_snapshots_user");

                    b.ToTable("trust_level_snapshots", "public", t =>
                        {
                            t.HasCheckConstraint("ck_trust_level_range", "level BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("email_verified_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("phone_verified_at_utc");

                    b.Property<string>("PreferredLocale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("de")
                        .HasColumnName("preferred_locale");

                    b.Property<string>("PrimaryAuthMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PhoneOtp")
                        .HasColumnName("primary_auth_method");

                    b.Property<bool>("SeniorModeDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("senior_mode_default");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email")
                        .HasFilter("email IS NOT NULL AND NOT is_deleted");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ux_users_phone")
                        .HasFilter("phone IS NOT NULL AND NOT is_deleted");

                    b.ToTable("users", "public", t =>
                        {
                            t.HasCheckConstraint("ck_users_auth_method", "primary_auth_method IN ('phone_otp','email_magic_link','password')");

                            t.HasCheckConstraint("ck_users_contact", "email IS NOT NULL OR phone IS NOT NULL");

                            t.HasCheckConstraint("ck_users_locale", "preferred_locale IN ('de','en','fa')");

                            t.HasCheckConstraint("ck_users_password_only_for_password_auth", "(primary_auth_method = 'password') = (password_hash IS NOT NULL)");

                            t.HasCheckConstraint("ck_users_phone_auth_needs_phone", "primary_auth_method <> 'phone_otp' OR phone IS NOT NULL");

                            t.HasCheckConstraint("ck_users_status", "status IN ('active','suspended','deactivated','deleted')");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Identity.Domain.UserCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capability");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("granted_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("GrantedByOrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_org_id");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Derived")
                        .HasColumnName("source");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_user_capabilities_expiring")
                        .HasFilter("expires_at_utc IS NOT NULL");

                    b.HasIndex("UserId", "Capability", "GrantedByOrgId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_capabilities");

                    b.ToTable("user_capabilities", "public", t =>
                        {
                            t.HasCheckConstraint("ck_user_capabilities_reason", "source = 'derived' OR reason IS NOT NULL");

                            t.HasCheckConstraint("ck_user_capabilities_source", "source IN ('derived','granted')");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Identity.Domain.Verification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text")
                        .HasColumnName("external_reference");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Manual")
                        .HasColumnName("provider");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("NotStarted")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("ValidUntilUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_until_utc");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("verified_at_utc");

                    b.Property<Guid?>("VerifiedByOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_organization_id");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ValidUntilUtc")
                        .HasDatabaseName("ix_verifications_expiring")
                        .HasFilter("status = 'verified' AND valid_until_utc IS NOT NULL");

                    b.HasIndex("UserId", "Type", "Status")
                        .HasDatabaseName("ix_verifications_user_type");

                    b.ToTable("verifications", "public", t =>
                        {
                            t.HasCheckConstraint("ck_verifications_provider", "provider IN ('manual','organization','id_austria','kyc')");

                            t.HasCheckConstraint("ck_verifications_status", "status IN ('not_started','pending','submitted','verified','rejected','expired')");

                            t.HasCheckConstraint("ck_verifications_type", "type IN ('email','phone','identity','address','organization','training','background_check')");

                            t.HasCheckConstraint("ck_verifications_verified_needs_date", "status <> 'verified' OR verified_at_utc IS NOT NULL");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.TrustSafety.Domain.VolunteerApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("applied_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at_utc");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("DeclineReason")
                        .HasColumnType("text")
                        .HasColumnName("decline_reason");

                    b.Property<string>("Motivation")
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("volunteer_applications", "public", t =>
                        {
                            t.HasCheckConstraint("ck_applications_decided_pair", "(decided_at_utc IS NULL) = (decided_by_user_id IS NULL)");

                            t.HasCheckConstraint("ck_applications_decline_reason", "status <> 'declined' OR decline_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_applications_status", "status IN ('open','approved','declined','withdrawn')");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.TrustSafety.Domain.VolunteerApplicationStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by_user_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset?>("OpenedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("opened_at_utc");

                    b.Property<int>("SlaDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(14)
                        .HasColumnName("sla_days");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("NotStarted")
                        .HasColumnName("status");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step");

                    b.HasKey("Id");

                    b.ToTable("volunteer_application_steps", "public", t =>
                        {
                            t.HasCheckConstraint("ck_application_steps_status", "status IN ('not_started','in_progress','completed','blocked','skipped')");

                            t.HasCheckConstraint("ck_application_steps_step", "step IN ('interview','background_check','confidentiality_agreement','briefing','approval')");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Organizations.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrandingJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("branding");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LegalName")
                        .HasColumnType("text")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("SupportEmail")
                        .HasColumnType("text")
                        .HasColumnName("support_email");

                    b.Property<string>("SupportPhone")
                        .HasColumnType("text")
                        .HasColumnName("support_phone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xmin");

                    b.HasKey("Id");

                    b.ToTable("organizations", "public", t =>
                        {
                            t.HasCheckConstraint("ck_organizations_status", "status IN ('active','suspended','archived')");

                            t.HasCheckConstraint("ck_organizations_type", "type IN ('ngo','association','parish','company','other')");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Organizations.Domain.OrganizationBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("organization_branches", "public", t =>
                        {
                            t.HasCheckConstraint("ck_branches_geo_pair", "(latitude IS NULL) = (longitude IS NULL)");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Organizations.Domain.OrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("JoinedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("joined_at_utc");

                    b.Property<DateTimeOffset?>("LeftAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("left_at_utc");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Invited")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("organization_memberships", "public", t =>
                        {
                            t.HasCheckConstraint("ck_memberships_role", "role IN ('staff','coordinator','admin','safeguarding_officer','volunteer','client')");

                            t.HasCheckConstraint("ck_memberships_status", "status IN ('invited','active','suspended','left')");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Organizations.Domain.OrganizationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PolicyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_key");

                    b.Property<string>("PolicyValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("policy_value");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("organization_policies", "public");
                });

            modelBuilder.Entity("SeniorConnect.Modules.Profiles.Domain.AvailabilitySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DayOfWeek")
                        .HasDatabaseName("ix_availability_user");

                    b.ToTable("availability_slots", "public", t =>
                        {
                            t.HasCheckConstraint("ck_availability_dow", "day_of_week BETWEEN 0 AND 6");

                            t.HasCheckConstraint("ck_availability_order", "start_time < end_time");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Profiles.Domain.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_key");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("interests", "public");
                });

            modelBuilder.Entity("SeniorConnect.Modules.Profiles.Domain.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iso_code");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_key");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("languages", "public");
                });

            modelBuilder.Entity("SeniorConnect.Modules.Profiles.Domain.SeniorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .HasColumnType("text")
                        .HasColumnName("address_line");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("AT")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("LivingSituation")
                        .HasColumnType("text")
                        .HasColumnName("living_situation");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MobilityNote")
                        .HasColumnType("text")
                        .HasColumnName("mobility_note");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("PreferredContactMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("App")
                        .HasColumnName("preferred_contact_method");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("VulnerabilityFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("vulnerability_flag");

                    b.Property<string>("VulnerabilityReason")
                        .HasColumnType("text")
                        .HasColumnName("vulnerability_reason");

                    b.Property<Guid?>("VulnerabilitySetByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("vulnerability_set_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("PostalCode")
                        .HasDatabaseName("ix_support_profiles_postal");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("ix_support_profiles_geo")
                        .HasFilter("latitude IS NOT NULL");

                    b.ToTable("support_profiles", "public", t =>
                        {
                            t.HasCheckConstraint("ck_support_contact_method", "preferred_contact_method IN ('app','phone','sms','family')");

                            t.HasCheckConstraint("ck_support_geo_pair", "(latitude IS NULL) = (longitude IS NULL)");

                            t.HasCheckConstraint("ck_support_vulnerability_reason", "NOT vulnerability_flag OR vulnerability_reason IS NOT NULL");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Profiles.Domain.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_key");

                    b.Property<bool>("RequiresVerification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_verification");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("skills", "public");
                });

            modelBuilder.Entity("SeniorConnect.Modules.Profiles.Domain.UserLanguage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Proficiency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("B1")
                        .HasColumnName("proficiency");

                    b.HasKey("UserId", "LanguageId");

                    b.ToTable("user_languages", "public", t =>
                        {
                            t.HasCheckConstraint("ck_user_languages_proficiency", "proficiency IN ('a1','a2','b1','b2','c1','c2','native')");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Profiles.Domain.VolunteerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActiveSinceUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("active_since_utc");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("HasCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_car");

                    b.Property<bool>("IsAcceptingRequests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_accepting_requests");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<short>("MaxActivitiesPerWeek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)3)
                        .HasColumnName("max_activities_per_week");

                    b.Property<int>("MaxDistanceKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("max_distance_km");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<decimal?>("ReliabilityScore")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("reliability_score");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("ix_volunteer_profiles_geo")
                        .HasFilter("latitude IS NOT NULL AND is_accepting_requests");

                    b.ToTable("volunteer_profiles", "public", t =>
                        {
                            t.HasCheckConstraint("ck_volunteer_distance", "max_distance_km BETWEEN 1 AND 100");

                            t.HasCheckConstraint("ck_volunteer_geo_pair", "(latitude IS NULL) = (longitude IS NULL)");

                            t.HasCheckConstraint("ck_volunteer_reliability", "reliability_score IS NULL OR reliability_score BETWEEN 0 AND 1");

                            t.HasCheckConstraint("ck_volunteer_weekly", "max_activities_per_week BETWEEN 1 AND 40");
                        });
                });

            modelBuilder.Entity("SeniorConnect.Modules.Profiles.Domain.VolunteerSkill", b =>
                {
                    b.Property<Guid>("VolunteerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("volunteer_profile_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("verified_at_utc");

                    b.Property<Guid?>("VerifiedByOrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_org_id");

                    b.HasKey("VolunteerProfileId", "SkillId");

                    b.ToTable("volunteer_skills", "public");
                });

            modelBuilder.Entity("user_interests", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("interest_id")
                        .HasColumnType("uuid")
                        .HasColumnName("interest_id");

                    b.HasKey("user_id", "interest_id");

                    b.HasIndex("interest_id");

                    b.ToTable("user_interests", "public");
                });

            modelBuilder.Entity("user_interests", b =>
                {
                    b.HasOne("SeniorConnect.Modules.Profiles.Domain.Interest", null)
                        .WithMany()
                        .HasForeignKey("interest_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeniorConnect.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
